name: ${name}
version: ${version}
main: me.duart.cucm.CustomUnknownCommandMessage
api-version: '${apiVersion}'
authors: [ ${authors} ]
description: ${description}

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false